language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
after_success:
  - codeclimate < ./bin/coverage/lcov.info
  - grunt sauce
addons:
  code_climate:
    repo_token:
      secure: "eaf0670f3843a1f392fd9fe8a9d3959aa285dcc594262ed2dd46f0d8321b9cd7"
  sauce_connect:
    username: "dylanpiercey"
    access_key: "07df8e16-a350-4ac3-92aa-8aaf6158bf01"
